#spring:
#  cloud:
#    globalcors:
#      cors-configurations:
#        '[/**]':
#          allowedOrigins: "*"
#          allowedHeaders: "*"
#          allowedMethods:
#            - GET
#            - POST
#            - PUT
#            - DELETE